[project]
name = "barcelonainnovationhub-2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "ipykernel>=7.1.0",
    "jupyter>=1.1.1",
    "kloppy>=3.18.0",
    "numpy>=2.4.1",
    "pandas>=3.0.0",
    "scikit-learn>=1.8.0",
    "skillcorner>=2.6.12",
    "mplsoccer (>=1.6.1,<2.0.0)",
    "sentence-transformers (>=5.2.2,<6.0.0)",
    "accelerate (>=1.12.0,<2.0.0)",
    "torch (>=2.10.0,<3.0.0)",
    "transformers (>=5.0.0,<6.0.0)",
    "openai (>=2.16.0,<3.0.0)",
    "highlight-text (>=0.2,<0.3)",
    "edge-tts (>=7.2.7,<8.0.0)",
    "nest-asyncio (>=1.6.0,<2.0.0)",
    "opencv-python (>=4.13.0.92,<5.0.0.0)",
    "mlx-vlm (>=0.3.11,<0.4.0)",
    "ollama (>=0.6.1,<0.7.0)",
    "faiss-cpu (>=1.13.2,<2.0.0)",
    "ipywidgets (>=8.1.8,<9.0.0)",
    "torchvision (>=0.25.0,<0.26.0)",
    "num2words (>=0.5.14,<0.6.0)",
    "av (>=16.1.0,<17.0.0)",
]

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
ruff = "^0.14.14"

